feat: learn ppc

diff --git a/C++/ppc/pre/prereq/grading b/C++/ppc/pre/prereq/grading
--- a/C++/ppc/pre/prereq/grading
+++ b/C++/ppc/pre/prereq/grading
@@ -1,1 +1,18 @@
-.ppc/grader.py
+#!/usr/bin/env sh
+
+grader=".ppc/grader.py"
+
+if [ -x "$grader" ]
+then
+    exec "$grader" "$@"
+elif [ -f "$grader" ]
+then
+    echo "error: No permission to run '$grader'. Try extracting the template archive with another program."
+elif [ "$0" != "./grading" ]
+then
+    echo "error: Cannot find file '$grader'. This script should be run from the same directory it is located in, as './grading'."
+else
+    echo "error: Missing file '$grader'. Make sure to extract the template archive in its entirety."
+fi
+
+exit 1
